services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

    environment:
      - spring.flyway.url=${FLYWAY_URL}
      - spring.r2dbc.url=${R2DBC_URL}
      - SPRING_PROFILES_ACTIVE=production
      - spring.flyway.cleanDisabled=true
      - spring.flyway.user=${DB_USERNAME}
      - spring.flyway.password=${DB_PASSWORD}
      - spring.r2dbc.username=${DB_USERNAME}
      - spring.r2dbc.password=${DB_PASSWORD}

    restart: unless-stopped