services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

    environment:
      - SPRING_PROFILES_ACTIVE=production
      - SPRING_FLYWAY_CLEANDISABLED=${SPRING_FLYWAY_CLEANDISABLED}
      - SPRING_FLYWAY_URL=${SPRING_FLYWAY_URL}
      - SPRING_R2DBC_URL=${SPRING_R2DBC_URL}
      - SPRING_FLYWAY_USER=${SPRING_FLYWAY_USER}
      - SPRING_FLYWAY_PASSWORD=${SPRING_FLYWAY_PASSWORD}
      - SPRING_R2DBC_USERNAME=${SPRING_R2DBC_USERNAME}
      - SPRING_R2DBC_PASSWORD=${SPRING_R2DBC_PASSWORD}
      - APP_ACCESS_TOKEN_SECRET=${APP_ACCESS_TOKEN_SECRET}
      - APP_REFRESH_TOKEN_SECRET=${APP_REFRESH_TOKEN_SECRET}

    restart: unless-stopped