services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

    environment:
      - SPRING_PROFILES_ACTIVE=production
      - spring.flyway.cleanDisabled=true
      - spring.flyway.url=jdbc:mysql://${DB_URL}:${DB_PORT}/${DB_NAME}${DB_PARAMS}
      - spring.r2dbc.url=r2dbc:mysql://${DB_URL}:${DB_PORT}/${DB_NAME}${DB_PARAMS}
      - spring.flyway.user=${DB_USERNAME}
      - spring.flyway.password=${DB_PASSWORD}
      - spring.r2dbc.username=${DB_USERNAME}
      - spring.r2dbc.password=${DB_PASSWORD}
      - app.access-token-secret=${ACCESS_TOKEN_SECRET}
      - app.refresh-token-secret=${REFERESH_TOKEN_SECRET}

    restart: unless-stopped