version: '3.7'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

    environment:
      - spring.flyway.url=jdbc:mysql://docker_db:3306/docker_db?autoReconnect=true&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
      - spring.r2dbc.url=r2dbc:mysql://docker_db:3306/docker_db?autoReconnect=true&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    restart: unless-stopped

networks:
  default:
    name: docker_db_mynetwork