spring:
  application:
    name: demo
  profiles:
    active: local

logging:
  level:
    org:
      springframework:
        web: DEBUG

app:
  token:
    secret: RANDOM_SECRET_FOR_JWT
    issuer: ${spring.application.name}
    expires-minute: 480
