secrets:
  spring:
    profiles:
    flyway:
      cleanDisabled: true
      url:
      user:
      password:
    r2dbc:
      url:
      username:
      password:
  app:
    access-token:
      secret:
    refresh-token:
      secret: