spring:
  application:
    name: demo

  config:
    import:
      - classpath:application-secrets.yml

  flyway:
    url: jdbc:mysql://${app.db.url}:${app.db.port}/${app.db.name}${app.db.params}
    user: ${app.db.username}
    password: ${app.db.password}
    baseline-on-migrate: true
    cleanDisabled: false

  r2dbc:
    url: r2dbc:mysql://${app.db.url}:${app.db.port}${app.db.params}
    name: ${app.db.name}
    username: ${app.db.username}
    password: ${app.db.password}
    pool:
      initial-size: 10
      max-size: 30
      max-idle-time: 15s
      validation-query: SELECT 1
    properties:
      connect-timeout: 10
      ssl: false
      max-create-connection-time: 3
      max-acquire-time: 5
      max-life-time: 15

app:
  token:
    issuer: ${spring.application.name}
  access-token:
    secret: ${app.access-token}
    expires-minute: 5
  refresh-token:
    secret: ${app.refresh-token}
    expires-minute: 20

logging:
  level:
    org:
      springframework:
        web: DEBUG