app:
  db:
    url: localhost
    port: 3306
    params:
    name: docker_db
    username: root
    password: root
  token:
    issuer: ${spring.application.name}
  access-token:
    secret: RANDOM_SECRET_FOR_ACCESS_TOKEN
  refresh-token:
    secret: OTHER_RANDOM_SECRET_FOR_REFRESH_TOKEN