spring:
  application:
    name: demo
  r2dbc:
    url:
    name:
    username:
    password:
    pool:
      initial-size: 10
      max-size: 30
      max-idle-time: 15s
      validation-query: SELECT 1
    properties:
      connect-timeout: 10
      ssl: false
      max-create-connection-time: 3
      max-acquire-time: 5
      max-life-time: 15
  flyway:
    url:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    baseline-on-migrate: true
    cleanDisabled: false

app:
  token:
    issuer: ${spring.application.name}
  access-token:
    secret:
    expires-minute: 5
  refresh-token:
    secret:
    expires-minute: 20

logging:
  level:
    org:
      springframework:
        web: DEBUG