spring:
  application:
    name: demo

  config:
    import:
      - classpath:application-secrets.yml

  flyway:
    url: ${secrets.spring.flyway.url}
    user: ${secrets.spring.flyway.user}
    password: ${secrets.spring.flyway.password}
    baseline-on-migrate: true
    clean-disabled: ${secrets.spring.flyway.clean-disabled}

  r2dbc:
    url: ${secrets.spring.r2dbc.url}
    username: ${secrets.spring.r2dbc.username}
    password: ${secrets.spring.r2dbc.password}
    pool:
      initial-size: 10
      max-size: 30
      max-idle-time: 15s
      validation-query: SELECT 1
    properties:
      connect-timeout: 10
      ssl: false
      max-create-connection-time: 3
      max-acquire-time: 5
      max-life-time: 15

server:
  port: 8080

app:
  allowed-origins: ${secrets.app.allowed-origins}
  token:
    issuer: ${spring.application.name}
  access-token:
    secret: ${secrets.app.access-token.secret}
    expires-minute: 50000
  refresh-token:
    secret: ${secrets.app.refresh-token.secret}
    expires-minute: 500000

logging:
  level:
    org:
      springframework:
        web: DEBUG
