spring:
  application:
    name: demo
  profiles:
    active: local

logging:
  level:
    org:
      springframework:
        web: DEBUG

app:
  token:
    issuer: ${spring.application.name}
  access-token:
    secret: RANDOM_SECRET_FOR_ACCESS_TOKEN
    expires-minute: 1
  refresh-token:
    secret: OTHER_RANDOM_SECRET_FOR_REFRESH_TOKEN
    expires-minute: 60
